In [ ]:
import feedparser
import pandas as pd

def get_bing_news(query, pages=2000):
    news_items = []
    for page in range(1, pages + 1):
        url = f"https://www.bing.com/news/search?q={query.replace(' ', '+')}&format=rss&first={page*10}"
        feed = feedparser.parse(url)
        
        for entry in feed.entries:
            news_items.append({
                'Date': entry.published,
                'Title': entry.title
            })
    return pd.DataFrame(news_items)

df = get_bing_news("Tata Motors", 2000)
print(df)

                                Date  \
0      Fri, 18 Jul 2025 02:33:00 GMT
1      Fri, 18 Jul 2025 05:54:09 GMT
2      Fri, 18 Jul 2025 06:39:10 GMT
3      Fri, 18 Jul 2025 07:02:36 GMT
4      Thu, 17 Jul 2025 22:42:00 GMT
...                              ...
15066  Mon, 02 May 2022 06:08:00 GMT
15067  Wed, 13 Oct 2021 08:57:00 GMT
15068  Mon, 28 Jun 2021 15:45:00 GMT
15069  Mon, 28 Jun 2021 07:57:00 GMT
15070  Thu, 16 Jun 2022 19:39:00 GMT

                                                   Title
0      Tata Group stocks: Tata Steel vs Trent vs Tita...
1      Tata Motors approaches Italy's Agnelli family ...
2      Tata Motors-owned JLR delays launch of Range R...
3      Iveco Is Said to Draw Takeover Interest From I...
4      Tata Punch Crosses 6 Lakh Sales Milestone In U...
...                                                  ...
15066  Tata Motors Ev Strategy: Tata, India's electri...
15067  Tata Motors offers TPG multiple exit options, ...
15068  Tata Motors plans 10 new electric vehicles by ...
15069  Tatas plan 10 EVs by 2025 in push towards sust...
15070  Tata Motors taking right actions to navigate c...

[15071 rows x 2 columns]

In [89]:
df.tail()

,Date,Timex,Title
15066,"Mon, 02 May 2022",22:42:00,"Tata Motors Ev Strategy: Tata, India's electri..."
15067,"Wed, 13 Oct 2021",22:42:00,"Tata Motors offers TPG multiple exit options, ..."
15068,"Mon, 28 Jun 2021",22:42:00,Tata Motors plans 10 new electric vehicles by ...
15069,"Mon, 28 Jun 2021",22:42:00,Tatas plan 10 EVs by 2025 in push towards sust...
15070,"Thu, 16 Jun 2022",22:42:00,Tata Motors taking right actions to navigate c...

In [84]:
df['Date'] = df['Date'].str[:-13]

In [99]:
df['Date'] = df['Date'].str[-11:]

In [ ]:
df

              Date                                              Title
0      18 Jul 2025  Tata Group stocks: Tata Steel vs Trent vs Tita...
1      18 Jul 2025  Tata Motors approaches Italy's Agnelli family ...
2      18 Jul 2025  Tata Motors-owned JLR delays launch of Range R...
3      18 Jul 2025  Iveco Is Said to Draw Takeover Interest From I...
4      17 Jul 2025  Tata Punch Crosses 6 Lakh Sales Milestone In U...
...            ...                                                ...
15066  02 May 2022  Tata Motors Ev Strategy: Tata, India's electri...
15067  13 Oct 2021  Tata Motors offers TPG multiple exit options, ...
15068  28 Jun 2021  Tata Motors plans 10 new electric vehicles by ...
15069  28 Jun 2021  Tatas plan 10 EVs by 2025 in push towards sust...
15070  16 Jun 2022  Tata Motors taking right actions to navigate c...

[15071 rows x 2 columns]

In [101]:
df.to_csv('headlines.csv', index = False)